// <auto-generated />
using System;
using Alugueis_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alugueis_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Alugueis_API.Models.Apto", b =>
                {
                    b.Property<int>("CodApto")
                        .HasColumnType("int");

                    b.Property<int>("Andar")
                        .HasColumnType("int");

                    b.Property<int>("CodPredio")
                        .HasColumnType("int");

                    b.Property<int>("MetrosQuadrados")
                        .HasColumnType("int");

                    b.Property<int>("QtdBanheiros")
                        .HasColumnType("int");

                    b.Property<int>("QtdQuartos")
                        .HasColumnType("int");

                    b.HasKey("CodApto");

                    b.HasIndex("CodPredio");

                    b.ToTable("Aptos");
                });

            modelBuilder.Entity("Alugueis_API.Models.Despesa", b =>
                {
                    b.Property<int>("CodDespesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodDespesa"));

                    b.Property<int>("CodTipoDespesa")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompetenciaMes")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDespesa")
                        .HasColumnType("datetime2");

                    b.Property<float>("VrlTotalDespesa")
                        .HasColumnType("real");

                    b.HasKey("CodDespesa");

                    b.HasIndex("CodTipoDespesa");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("Alugueis_API.Models.DespesaRateio", b =>
                {
                    b.Property<int>("CodDespesa")
                        .HasColumnType("int");

                    b.Property<int>("CodApto")
                        .HasColumnType("int");

                    b.Property<float>("VlrRateio")
                        .HasColumnType("real");

                    b.HasKey("CodDespesa", "CodApto");

                    b.HasIndex("CodApto");

                    b.ToTable("DespesaRateios");
                });

            modelBuilder.Entity("Alugueis_API.Models.Locacao", b =>
                {
                    b.Property<int>("CodLocacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodLocacao"));

                    b.Property<int>("CodApto")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataIncio")
                        .HasColumnType("datetime2");

                    b.Property<float>("VlrAluguel")
                        .HasColumnType("real");

                    b.Property<float>("VlrCausao")
                        .HasColumnType("real");

                    b.Property<int>("codLocatario")
                        .HasColumnType("int");

                    b.HasKey("CodLocacao");

                    b.HasIndex("CodApto");

                    b.HasIndex("codLocatario");

                    b.ToTable("Locacoes");
                });

            modelBuilder.Entity("Alugueis_API.Models.Locatario", b =>
                {
                    b.Property<int>("CodLocatario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodLocatario"));

                    b.Property<int>("CodPessoa")
                        .HasColumnType("int");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<int?>("PessoaCodPessoa")
                        .HasColumnType("int");

                    b.Property<int>("QtdDependentes")
                        .HasColumnType("int");

                    b.Property<int>("TemPet")
                        .HasColumnType("int");

                    b.HasKey("CodLocatario");

                    b.HasIndex("PessoaCodPessoa");

                    b.ToTable("Locatarios");
                });

            modelBuilder.Entity("Alugueis_API.Models.Pessoa", b =>
                {
                    b.Property<int>("CodPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodPessoa"));

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoCivil")
                        .HasColumnType("int");

                    b.Property<string>("NomePessoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodPessoa");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("Alugueis_API.Models.Predio", b =>
                {
                    b.Property<int>("CodPredio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodPredio"));

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePredio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QtdAndares")
                        .HasColumnType("int");

                    b.HasKey("CodPredio");

                    b.ToTable("Predios");
                });

            modelBuilder.Entity("Alugueis_API.Models.TipoDespesa", b =>
                {
                    b.Property<int>("CodTipoDespesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodTipoDespesa"));

                    b.Property<int>("Compartilhado")
                        .HasColumnType("int");

                    b.Property<string>("NomeTipoDespesa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodTipoDespesa");

                    b.ToTable("TiposDespesa");
                });

            modelBuilder.Entity("Alugueis_API.Models.Usuario", b =>
                {
                    b.Property<int>("CodUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodUsuario"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("CodPessoa")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<byte[]>("SenhaHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SenhaSalt")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("CodUsuario");

                    b.HasIndex("CodPessoa")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Alugueis_API.Models.Apto", b =>
                {
                    b.HasOne("Alugueis_API.Models.Predio", "Predio")
                        .WithMany("Aptos")
                        .HasForeignKey("CodPredio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predio");
                });

            modelBuilder.Entity("Alugueis_API.Models.Despesa", b =>
                {
                    b.HasOne("Alugueis_API.Models.TipoDespesa", "TipoDespesa")
                        .WithMany("Despesas")
                        .HasForeignKey("CodTipoDespesa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoDespesa");
                });

            modelBuilder.Entity("Alugueis_API.Models.DespesaRateio", b =>
                {
                    b.HasOne("Alugueis_API.Models.Apto", "Apto")
                        .WithMany("DespesasRateio")
                        .HasForeignKey("CodApto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alugueis_API.Models.Despesa", "Despesa")
                        .WithMany("Rateios")
                        .HasForeignKey("CodDespesa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apto");

                    b.Navigation("Despesa");
                });

            modelBuilder.Entity("Alugueis_API.Models.Locacao", b =>
                {
                    b.HasOne("Alugueis_API.Models.Apto", "Apto")
                        .WithMany("Locacoes")
                        .HasForeignKey("CodApto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alugueis_API.Models.Locatario", "Locatario")
                        .WithMany("Locacoes")
                        .HasForeignKey("codLocatario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apto");

                    b.Navigation("Locatario");
                });

            modelBuilder.Entity("Alugueis_API.Models.Locatario", b =>
                {
                    b.HasOne("Alugueis_API.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaCodPessoa");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Alugueis_API.Models.Usuario", b =>
                {
                    b.HasOne("Alugueis_API.Models.Pessoa", "Pessoa")
                        .WithOne("Usuario")
                        .HasForeignKey("Alugueis_API.Models.Usuario", "CodPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Alugueis_API.Models.Apto", b =>
                {
                    b.Navigation("DespesasRateio");

                    b.Navigation("Locacoes");
                });

            modelBuilder.Entity("Alugueis_API.Models.Despesa", b =>
                {
                    b.Navigation("Rateios");
                });

            modelBuilder.Entity("Alugueis_API.Models.Locatario", b =>
                {
                    b.Navigation("Locacoes");
                });

            modelBuilder.Entity("Alugueis_API.Models.Pessoa", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Alugueis_API.Models.Predio", b =>
                {
                    b.Navigation("Aptos");
                });

            modelBuilder.Entity("Alugueis_API.Models.TipoDespesa", b =>
                {
                    b.Navigation("Despesas");
                });
#pragma warning restore 612, 618
        }
    }
}
